remote_theme: BDHU/minimalist
title: Portfolio of Anton HÃ¶rig
description: BSc in Media Computer Science. Passionate about GameDev & Computer Graphics.
logo: /media/ProfilePictureLight.png
color-scheme: auto

sidebar:
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:mail@antonhoerig.de
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://linkedin.com/in/anton-hoerig
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/maantho

plugins:
  - jekyll-remote-theme