theme: jekyll-theme-minimal
title: Portflolio of Anton HÃ¶rig
description: BSc in Media Computer Science. Passionate about GameDev & Computer Graphics. \n https://itch.io/jam/mini-jame-gam-36
logo: /media/ProfilePictureLight.png