remote_theme: BDHU/minimalist
title: Portfolio of Anton HÃ¶rig
description: BSc in Media Computer Science. Passionate about GameDev & Computer Graphics.
logo: /media/ProfilePictureLight.png
color-scheme: auto

plugins:
  - jekyll-remote-theme